### ISSUE TITLE
Use 1.10 structure blocks to mark cuboid selections

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#23]
It would be nice to show overlays without client mods.

However, they are limited to 32x32x32 cuboids, the structure block needs to be to the player, if it gets too far the lines won't be displayed even if the player is close to the them.

Multiple structure blocks could be used to show bigger selections and with different shapes by creating thin walls instead of cubes and bricking them together.

Bukkit does not provide API to create that fake blocks with fake tile entities, so that feature would work only on Forge servers.

**Comment by joserobjr** [comment]
Unfortunately, the overlay is not rendered in survival mode,, so it's not an option. Sad, it was getting cool.
![2016-09-03_12 03 47](https://cloud.githubusercontent.com/assets/3679022/18225680/91953a94-71ce-11e6-9418-f27ffa9c9185.png)

**Comment by LucasPMagno** [comment]
I know it has the Won't Fix label but you could try to use falling sand entity's textured to glass with no gravity, just an idea, do you prefer to open/comment issues in English or Portuguese? I am fluent in both.

**Comment by joserobjr** [comment]
Good idea, I could apply glow effect to it and it would be visible through blocks. I'm going to open a new issue with your suggestion.

> do you prefer to open/comment issues in English or Portuguese? I am fluent in both.
Write in English if you can
