### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by Eufranio** [GameModsBR/MineCity#31]
Is there releases of MineCity? Also, is there a jenkins with latest builds?

**Comment by joserobjr** [comment]
Not yet.

To build from the source run:
```bash
gradlew setupDecompWorkspace
gradlew build
```

The Bukkit plugin will be at Bukkit\build\libs
The Forge mods will be at Forge\X.X.X\build\libs

Use the Bukkit plugin in vanilla servers like CraftBukkit, Spigot, PaperSpigot
Use a Forge mod in servers with Forge, like a pure Forge server, SpongeForge, Cauldron, kCauldron, Thermos.

Do not mix the plugin with the mod, use only one jar.

The Bukkit plugin only supports 1.10.2 now, I'll add backyard compatibility up to 1.8 later, I'm testing with CraftBukkit and Spigot servers but feel free to test with other softwares like PaperSpigot.

There're forge mods for 1.7.10 and 1.10.2, I'll add support for 1.8.9 and 1.9.4 later. I'm testing with pure forge for now, Thermos and softwares that mixes Bukkit with Forge might have some unchecked incompatibilities right now, it may or may not work.

**Comment by RumpeSan** [comment]
José, mais uma vez unica forma de encontrar você: ambos o servidores estão off-line e forum também desde a madrugada de hoje (02/09), aparentemente até o ts está com problemas, preciso falar contigo também sobre algumas coisas do servidor se puder entrar em contato agradeço.

**Comment by joserobjr** [comment]
@RumpeSan o provedor está fazendo uma manutenção no sistema de backup e por isso está tudo off.

**Comment by RumpeSan** [comment]
Quando o ts voltar podemos conversar? Gostaria de falar sobre algumas regras que acho que deveríamos entrar no industrial e pedir pra vc investigar algumas coisas pelo log, mas o mais importante talvez seja: eu vou ter apenas os mesmos "poderes" dos moderadores do sabotador? Você tinha comentado que eu poderia forçar um backup manual caso desse erro mas tanto não consigo fazer isso depois do rollback como não aparece mais a mensagem no chat que está fazendo backup... E o mod da cidade acha que está perto de finalizar?

**Comment by joserobjr** [comment]
@RumpeSan Cria um issue de pergunta, ficar indo de uma issue para outra para responder não está legal huahua.

Depois dessa lista: https://github.com/GameModsBR/MineCity/issues/10 vou começar a fazer as proteções para os mods. Acredito que não irei levar tanto tempo entre cada mod pela forma que projetei a proteção para forge.
