### ISSUE TITLE
RayTraceResult is not being patched

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#33]
The interface `IRayTraceResult` is not being applied.

**Comment by fesnadi** [comment]
José os servidores e o fórum está ofline, acho que derrubaram de novo!

**Comment by RumpeSan** [comment]
José para de tomar chá de sumiço com biscoito de cadê você, estou guardando e anotando bastante alguns tópicos que acho que precisam ser revisados ou adicionados, mas desde a madrugada de hoje tanto fórum quanto ts quanto ambos servidores estão off é aqui é único lugar que consigo mandar msg de forma que você veja relativamente rápido espero que o motivo de estar tudo off seja algo simples ou você mexendo...

**Comment by joserobjr** [comment]
@fesnadi O servidor está em manutenção pelo provedor de hospedagem, estão ajustando o serviço de backup e logo irá voltar.

@RumpeSan Queria eu tomar chá de sumiço mas estou aqui trabalhando feito louco para o MineCity ficar pronto, só ver o histórico de commits...

A maior parte dos problemas com o industrial vão sumir quando o MineCity entrar em jogo

**Comment by RumpeSan** [comment]
@joserobjr o industrial bugou de novo (não sei horario) mas assim que você loga ou é crash instantâneo ou vc fica on alguns instantes com o bug de ID novamente fui notificado por um jogador, e fui conferir tentei duas vezes e tomei crash instantâneo ao logar no industrial, espero q tenha backup de ontem a noite ou pelo menos algo muito proximo de antes do bug e começo a achar que existe uma forma de provocar esse crash já não é nem a primeira nem a segunda vez que acontece supostamente do nada...

**Comment by RumpeSan** [comment]
falta muito para acabar o minecity? e o industrial ficaria mais facil resetar e colocar na 1.10 ? sistema de backup falta muito?

**Comment by joserobjr** [comment]
O sistema de backup já está funcionando, estou deixando mais um pouco para confirmar que está tudo certo.

Não vou mudar a versão e vou tentar recuperar sem restaurar, ainda existe uma possibilidade de salvar então não vou abandona-la.

> falta muito para acabar o minecity?

Veja os milestones e os issues com lista de progressos e você terá uma boa noção do progresso

**Comment by RumpeSan** [comment]
@joserobjr o industrial volta esse ano? você não da noticias sobre o progresso real do servidor :(
