### ISSUE TITLE
Plot ghost blocks disappear when the shouldn't and plot creation tool stays with you

### ISSUE THREAD

**Issue by LucasPMagno** [GameModsBR/MineCity#54]
Not all of them but some when I step on them or when I enter the block next to them they disappear it isn't that big of a deal but it does get pretty annoying sometimes. the tool isn't deleted after the creation of the plot so some people could end up with hundreds of them, with the recycler from IC2 enabled that could become a problem

**Comment by ETblaky** [comment]
I can't create a plot, it just says "Stand inside the plot and execute this command again." even when you are inside, am i the only one having this issue?
