### ISSUE TITLE
Bug no sabotage

### ISSUE THREAD

**Issue by UmModderQualquer** [GameModsBR/MineCity#69]
Como você não entra no fórum faz um tempo, e está ativo por aqui acho que esse é o melhor lugar pra avisa você que ao entrar no sabotage pelo sabotador.com dá erro para alguns jogadores(acho que é a maioria, pois o servidor está vazio), mas alguns jogadores estão conseguindo entrar por esse ip. Uma solução que eu encontrei para entrar é usar o ip gamemods.com.br, testei ele e consegui entrar sem problemas.

**Comment by joserobjr** [comment]
Obrigado por avisar, vou verificar o que está acontecendo agora.

**Comment by Eufranio** [comment]
vulgo natan12 dupper
