### ISSUE TITLE
Bukkit Protections

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#9]
## Enter
- [x] Walking
- [x] Flying
- [x] Elytra
- [x] Boat
- [x] Land Vehicle
- [x] Attempt to mount on a vehicle there is where the player can't enter
- [x] By nether portals

## Pickup
- [x] Pickup drops
- ~~Pickup experience~~ _Bukkit does not provide the necessary API for this_
- ~~Push experience~~ _Bukkit does not provide the necessary API for this_
- [x] Deny pickup arrow from others
- [x] Allow picking up his own arrows
- [x] Do not let drop if the player can't picking up
- [x] Allow to pickup back if the player managed to drop
- [x] Allow to picking up back the drops from death
- [x] Collect the fish he fished
- [x] Pull items with fishing rod that he can get

## Ride
- [x] Enter ridding
- [x] Mount a saddled pig
- [x] Mount a horse
- [x] Mount a minecart

## Spawn Vehicle
- [x] Place minecarts
- [x] Place boats
- [x] Get minecart back
- [x] Get boat back

## Harvest
- [x] Sugar cane
- [x] Cactus
- [x] Crops
- [x] Replant crops when the player can harvest but can't modify
- [x] Milk from cows
- [x] Soup from mushroom cows
- [x] Villagers
- [x] Allow using bone meal where the player can harvest but can't modify
- [x] Allow picking up harvested items even when the player has no permission to pickup
- [x] Shear sheep

## Modify
- [x] Place non-ridable minecarts
- [x] Spawn chickens with eggs shooting a boat
- [x] Spawn chickens with eggs shooting a wall
- [x] Spawn chickens with eggs shooting an entity
- [x] Spawn endermites with ender pearls hitting boats
- [x] Spawn endermites with ender pearls hitting walls
- [x] Spawn endermites with ender pearls hitting entities
- [x] Saddle / Armor horse that was not tamed by the player (needs to check the inventory GUI)
- [x] Put chest in a donkey
- [x] Steal donkey's chest contents
- [x] Saddle a pig
- [x] Place block
- [x] Break block
- [x] Break boats directly
- [x] Break boats with bow
- [x] Break boats with dispenser
- [x] Break minecarts directly
- [x] Break minecarts with bow
- [x] Break minecarts with dispenser
- [x] Break paintings
- [x] Place paintings
- [x] Place big paintings from outside
- [x] Break item frames
- [x] Place item frames
- [x] Liquid flow
- [x] Filling bucket
- [x] Emptying bucket
- [x] Trample crops
- [x] Activate Ender Crystal
- [x] Damage Ender Crystal
- [x] Tame an untamed wolf
- [x] Tame an untamed ocelot
- [x] Convert a named zombie into a villager
- [x] Unleash a hitch
- [x] Activate an explosive minecart
- [x] Make sand, gravel, dragon egg, anvil enter where the player can't modify with bouncers
- [x] Make sand, gravel, dragon egg, anvil enter where the player can't modify placing above
- [x] Make sand, gravel, dragon egg, anvil enter where the player can't modify breaking its support
- [x] Make sand, gravel, dragon egg, anvil enter where the player can't modify placing water under it
- [x] Place an armor stand inside
- [x] Place an armor stand above
- [x] Place an armor stand above and then breaking the support block
- [x] Place an armor stand bouncing it from outside
- [x] Explosion
- [x] Shooting a TNT with a fire arrow
- [x] Luring creepers
- [x] Luring endermans
- [x] With nether portals coming from the other dimension
- [x] With direct bone meal on dirt
- [x] Affecting blocks using bone meal outside
- [x] Growing tree
- [x] Growing giant mushrooms
- [x] Using bone meal on protected saplings
- [x] Using bone meal on protected mushrooms
- [x] Ride entity to outside
- [x] Push any entity to outside
- [x] Entity naturally wandering to outside
- [x] Push horses to outside
- [x] Horses naturally wandering to outside
- [x] Luring entities to outside
- [x] Killing named monsters
- [x] Grass, mycelium spread
- [x] Fire spread
- [x] Vine spread
- [x] Mushroom spread 
- [x] Frost walker
- [x] Pumpkin / Melon growing from outside to inside
- [x] Right click a protected ender egg
- [x] Right click an unprotected ender egg to make it teleport to a protected zone
- [x] Ender egg entering the zone without right clicks
- [x] Placing end crystals
- [x] Forming a nether portal in a protected obsidian
- [x] Forming entity (golems, wither) when it's split into different plots
- [x] Push block with piston
- [x] Pull block with piston
- [x] Spawning mobs with spawn eggs
- [x] Bone meal on a tall grass
- [x] Hoe on dirt / grass
- [x] Shovel on grass
- [x] Placing bed from outside
- [x] Pulling entities with fishing rod
- [x] Forming nether portal where the portal is split in an area without modifying permission
- [x] Leashing entities
- [x] Building a snowman and letting it escape
- [x] Enderman

## Open
- [x] Change armor stands
- [x] Storage Minecarts
- [x] Hopper Minecarts
- [x] Item Frames
- [x] Chests
- [x] Trapped Chests
- [x] Furnaces
- [x] Hoppers
- [x] Anvil
- [x] Droppers
- [x] Dispensers
- [x] Beacon
- [x] Brewing Stands
- [x] Modify containers with hoppers

## Click
- [x] Click on powered Minecarts
- [x] On wood buttons with bow
- [x] On wood pressure plates with bow
- [x] Collect dragon breath
- [x] Enchanting table
- [x] Crafting table
- [x] Buttons
- [x] Levelers
- [x] Doors
- [x] Open ender chest

## PVP
- [x] Directly attack a player
- [x] Attack a player with a projectile
- [x] Attack a player with a dispenser
- [x] Attack a player with potions
- [x] Attack with a wolf
- [x] Make the wolf stop the attack
- [x] With explosion
- [x] Allow collecting loot even if pickup is denied
- [x] Pull players with fishing rod
- [x] Add negative effects with potions
- [x] Add negative effects with area effect cloud

## PVC
- [x] Directly attack an animal
- [x] Attack an animal with a projectile
- [x] Attack a creature with a dispenser
- [x] Attack an animal with potions
- [x] Attack an animal with a wolf
- [x] Make the wolf stop the attack
- [x] With explosion
- [x] Allow collecting loot even if pickup is denied
- [x] Pull animals with fishing rod
- [x] Add negative effects with potions
- [x] Add negative effects with area effect cloud
- [x] Breeding animals

## PVM
- [x] Directly attack a monster
- [x] Attack a monster with a projectile
- [x] Attack a monster with a dispenser
- [x] Attack a monster with potions
- [x] Attack a monster with a wolf
- [x] Make the wolf stop the attack
- [x] With explosion
- [x] Allow collecting loot even if pickup is denied
- [x] Pull monsters with fishing rod
- [x] Add negative effects with potions
- [x] Add negative effects with area effect cloud

**Comment by RumpeSan** [comment]
Jose o servidor está dando backup failed ja a um tempo como nao consigo falar com você pelo ts e não consigo dar /backup de jeito nenhum tive que arriscar de conseguir falar com vc por aqui espero que veja minha mensagem ç.ç

**Comment by joserobjr** [comment]
Obrigado por avisar
