### ISSUE TITLE
/rtp teleports to underground

### ISSUE THREAD

**Issue by LucasPMagno** [GameModsBR/MineCity#92]
/rtp teleported me underground 
![2016-11-14_20 45 35](https://cloud.githubusercontent.com/assets/21979647/20290033/8876811e-aaab-11e6-9e52-58e4f2710dda.png)
The surface (I think it tried to teleport me on the block behind the leave and then somehow I ended up a couple blocks beneath it):
![2016-11-14_20 48 04](https://cloud.githubusercontent.com/assets/21979647/20290070/cc315302-aaab-11e6-8b81-67debfbe4cc0.png)

**Comment by joserobjr** [comment]
Sorry, this is not caused by MineCity, but I'm going to register it as a issue in GameMods Industrial.
