### ISSUE TITLE
Error when selling lot

### ISSUE THREAD

**Issue by jonatsp** [GameModsBR/MineCity#94]
When trying to sell a lot, I get the message that says I have to be inside the lot, being that I am inside the lot 
Screenshot: http://prnt.sc/d7rtt0

**Comment by ChampsBR** [comment]
Desculpe pelo meu inglês.

**Comment by joserobjr** [comment]
I think that you are just outside the plot or you've created a plot with 1 block height :P
Does /lote info shows the plot information?
